export type Fundamentals = {
    "50DayMovingAverage": string,
    "52WeekHigh": string,
    "52WeekLow": string,
    "200DayMovingAverage": string,
    "Address": string,
    "AnalystTargetPrice": string,
    "AssetType": string,
    "Beta": string,
    "BookValue": string,
    "CIK": string,
    "Country": string,
    "Currency": string,
    "Description": string,
    "DilutedEPSTTM": string,
    "DividendDate": string,
    "DividendPerShare": string,
    "DividendYield": string,
    "EBITDA": string,
    "EPS": string,
    "EVToEBITDA": string,
    "EVToRevenue": string,
    "ExDividendDate": string,
    "Exchange": string,
    "FiscalYearEnd": string,
    "ForwardPE": string,
    "GrossProfitTTM": string,
    "Industry": string,
    "LatestQuarter": string,
    "MarketCapitalization": string,
    "Name": string,
    "OperatingMarginTTM": string,
    "PEGRatio": string,
    "PERatio": string,
    "PriceToBookRatio": string,
    "PriceToSalesRatioTTM": string,
    "ProfitMargin": string,
    "QuarterlyEarningsGrowthYOY": string,
    "QuarterlyRevenueGrowthYOY": string,
    "ReturnOnAssetsTTM": string,
    "ReturnOnEquityTTM": string,
    "RevenuePerShareTTM": string,
    "RevenueTTM": string,
    "Sector": string,
    "SharesOutstanding": string,
    "Symbol": string,
    "TrailingPE": string,
}

export type IncomeReport = {
    comprehensiveIncomeNetOfTax: string,
    costOfRevenue: string,
    costofGoodsAndServicesSold: string,
    depreciation: string,
    depreciationAndAmortization: string,
    ebit: string,
    ebitda: string,
    fiscalDateEnding: string,
    grossProfit: string,
    incomeBeforeTax: string,
    incomeTaxExpense: string,
    interestAndDebtExpense: string,
    interestExpense: string,
    interestIncome: string,
    investmentIncomeNet: string,
    netIncome: string,
    netIncomeFromContinuingOperations: string,
    netInterestIncome: string,
    nonInterestIncome: string,
    operatingExpenses: string,
    operatingIncome: string,
    otherNonOperatingIncome: string,
    researchAndDevelopment: string,
    sellingGeneralAndAdministrative: string,
    totalRevenue: string,
}

export type Income = {
    symbol: string,
    annualReports: IncomeReport[],
    quartlyReports: IncomeReport[];
}
